Traceback (most recent call last):
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'batch_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 335, in <module>
    main()
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 214, in main
    train_dataloader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, collate_fn=collate_fn)
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'batch_size'
Traceback (most recent call last):
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'batch_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 335, in <module>
    main()
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 214, in main
    train_dataloader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, collate_fn=collate_fn)
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'batch_size'
