[34m[1mwandb[0m: [32m[41mERROR[0m You must call wandb.init() before wandb.config.batch_size
Traceback (most recent call last):
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 335, in <module>
    main()
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 214, in main
    train_dataloader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, collate_fn=collate_fn)
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\lib\preinit.py", line 27, in __getattr__
    raise wandb.Error(f"You must call wandb.init() before {self._name}.{key}")
wandb.errors.errors.Error: You must call wandb.init() before wandb.config.batch_size
Traceback (most recent call last):
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 335, in <module>
    main()
  File "D:\github\Cricket-Prediction\training\pytorch\prerp_augmented.py", line 214, in main
    train_dataloader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, collate_fn=collate_fn)
  File "C:\Users\chavv\anaconda\envs\huggingface-torch\lib\site-packages\wandb\sdk\lib\preinit.py", line 27, in __getattr__
    raise wandb.Error(f"You must call wandb.init() before {self._name}.{key}")
wandb.errors.errors.Error: You must call wandb.init() before wandb.config.batch_size
